name: CI

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
      - add-arm64-executable
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

  publish:
    needs: build
    runs-on: ubuntu-latest-arm64
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-latest]
        architecture: [arm64, x64]

    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Build
        run: go build -o openapi-oathkeeper

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            openapi-oathkeeper
            
  